### ISSUE TITLE
please add shasta

### ISSUE THREAD

**Issue by colindaven** [nadegeguiglielmoni/genome_assembly_tools#3]
hello, thanks for a nice repo.

Can you please add shasta to the noisy long read section (ONT). 

https://github.com/paoloshasta/shasta

Thanks,
Colin

**Comment by nadegeguiglielmoni** [comment]
Hello,

Thank you for pointing it out, it should already have been there as it is already in the paper. Sorry for taking so much time to add it, the whole summer has been very busy.
